name: aquater_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- TUS LIBRERÍAS ---
  firebase_core: ^3.1.0
  flutter_email_sender: ^6.0.2
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  signature: ^5.4.1        # <--- Librería para la pizarra de firma
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  mailer: ^6.0.0
  pdf: ^3.10.7
  printing: ^5.11.0
  cupertino_icons: ^1.0.8
  flutter_image_compress: ^2.4.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # --- ASSETS (Imágenes) ---
  assets:
    - assets/images/logo_aquater.png
    - assets/images/logo_duoc.png
    - assets/images/pie_pagina.png
    # --- NUEVOS LOGOS ---
    - assets/images/logo_iss.png
    - assets/images/logo_ventisquero.png
    # Firmas:
    - assets/images/firma_jorge.png
    - assets/images/firma_marco.png
    - assets/images/firma_maximiliano.png
    - assets/images/firma_gustavo.png