name: aquater_app
description: "Software Tecnico Aquater Ltda."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI & UTILIDADES ---
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  
  # --- MAPAS ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
    
  # --- FIREBASE (VERSIONES ACTUALIZADAS PARA CORREGIR ERROR) ---
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.1
  
  # --- FUNCIONALIDADES TÉCNICAS ---
  signature: ^5.4.1           # Firma digital
  image_picker: ^1.0.4        # Cámara y Galería
  path_provider: ^2.1.1       # Rutas de archivos
  flutter_image_compress: ^2.1.0 # Compresión de fotos
  fl_chart: ^0.66.0           # Gráficos

  # --- PDF Y CORREO ---
  pdf: ^3.10.4
  printing: ^5.11.1
  mailer: ^6.0.0              # Envío SMTP (Gmail)
  flutter_email_sender: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # --- GENERADORES DE ASSETS ---
  flutter_launcher_icons: ^0.13.1  # Icono de la App
  flutter_native_splash: ^2.3.10   # Pantalla de Carga (Nuevo)

flutter:
  uses-material-design: true

  # --- ASSETS (IMÁGENES) ---
  assets:
    - assets/images/logo_aquater.png
    - assets/images/logo_duoc.png
    - assets/images/pie_pagina.png
    # LOGOS CLIENTES
    - assets/images/logo_iss.png
    - assets/images/logo_ventisquero.png
    # FIRMAS TÉCNICOS
    - assets/images/firma_jorge.png
    - assets/images/firma_marco.png
    - assets/images/firma_maximiliano.png
    - assets/images/firma_gustavo.png

# --- CONFIGURACIÓN 1: ICONO DE LA APP ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo_aquater.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_aquater.png"

# --- CONFIGURACIÓN 2: PANTALLA DE CARGA (SPLASH) ---
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo_aquater.png"
  android_12:
    image: "assets/images/logo_aquater.png"
    color: "#ffffff"